USE user_schema;
INSERT INTO users (first_name, last_name, email) VALUES ('Mike', 'Tyson', 'MikeTyson@gmail.com');
INSERT INTO users (first_name, last_name, email) VALUES ('Cobi', 'Jones', 'CobiJones@soccer.com');
INSERT INTO users (first_name, last_name, email) VALUES ('Emeril', 'Legasse', 'EmerilLegasse@gmail.com');
SELECT * FROM users;
SELECT * FROM users WHERE email = "MikeTyson@gmail.com";
SELECT * FROM users WHERE id = 3;
UPDATE users SET last_name = "Pancakes" WHERE id = 3;
DELETE FROM users WHERE id = 2;
SELECT * FROM users ORDER BY first_name;
SELECT * FROM users ORDER BY first_name DESC;